springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api=docs
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
      authentication-database: admin
      username: admin
      password: admin
