spring:
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/jobzilla
    username: admin
    password: admin
  r2dbc:
    url: r2dbc:mysql://localhost:3306/jobzilla
    username: admin
    password: admin
